# Generated by Django 4.1.5 on 2023-01-07 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_audio_is_converted_alter_audio_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 6, 18, 37, 196049, tzinfo=datetime.timezone.utc)),
        ),
    ]
