# Generated by Django 4.1.4 on 2023-01-07 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_audio_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 20, 44, 32, 552578, tzinfo=datetime.timezone.utc)),
        ),
    ]
