# Generated by Django 4.1.4 on 2023-01-07 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_audio_duration_audio_name_alter_audio_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 21, 49, 51, 58319, tzinfo=datetime.timezone.utc)),
        ),
    ]
