# Generated by Django 4.1.4 on 2023-01-07 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_audio_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(default='helo', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 22, 10, 9, 862907, tzinfo=datetime.timezone.utc)),
        ),
    ]
